<?php
//echo $_SERVER['REMOTE_ADDR'];
//
//function checkSoton() {
//
//    //if (substr($_SERVER['REMOTE_ADDR'],0,7) == "152.78.") {
//    if (substr($_SERVER['REMOTE_ADDR'],0,7) == "127.0.0") {
//        return TRUE;
//
//    } else {
//        return FALSE;
//    }
//}
//
//if (!checkSoton()) {
//    exit("You are not authorised to view this page.");
//} ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="css/nihr-colours.css" type="text/css">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    </head>
    <body>
        <div class="container-fluid">
            <div class="jumbotron">
                <h1>Welcome to NETSCC Business Intelligence</h1>
            </div>
            <div class="panel-group" id="accordion">
                <div class="funding panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse1"><img src="images/excel.svg">
                                NETSCC - Key Reports & Datasets</a>
                        </h4>
                    </div>
                    <div id="collapse1" class="panel-collapse collapse in">
                        <div class="panel-body list-group">
                            <a href="" class="list-group-item" >Application Cost Charges</a>
                            <a href="" class="list-group-item" >Burden of Disease</a>
                            <a href="" class="list-group-item" >Call Success Rates</a>
                        </div>
                    </div>
                </div>
                <div class="ppi panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse2"><img src="images/dashboard.jpg">
                                NETSCC Dashboards (QlikView)</a>
                        </h4>
                    </div>
                    <div id="collapse2" class="panel-collapse collapse">
                        <div class="panel-body list-group">
                            <a href="" class="list-group-item" >Data Quality Dashboard</a>
                            <a href="" class="list-group-item" >Finance Dashboard</a>
                            <a href="" class="list-group-item" >Monitoring Dashboard</a>
                        </div>
                    </div>
                </div>
                <div class="nihrarea panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse3"><img src="images/sharepoint.png">
                                SharePoint Reporting Services Reports</a>
                        </h4>
                    </div>
                    <div id="collapse3" class="panel-collapse collapse">
                        <div class="panel-body list-group">URLs to go here

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
