<?php
//echo $_SERVER['REMOTE_ADDR'];
//
//function checkSoton() {
//
//    //if (substr($_SERVER['REMOTE_ADDR'],0,7) == "152.78.") {
//    if (substr($_SERVER['REMOTE_ADDR'],0,7) == "127.0.0") {
//        return TRUE;
//
//    } else {
//        return FALSE;
//    }
//}
//
//if (!checkSoton()) {
//    exit("You are not authorised to view this page.");
//} ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="css/nihr-colours.css" type="text/css">
        <link rel="stylesheet" href="css/portal.css" type="text/css">
        <link rel="stylesheet" href="css/3-col-portfolio.css" type="text/css">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    </head>
    <body>
    <div class="container-fluid wrapper body-wrapper">
<!--        <div class="netscc-banner">-->
<!--            <ul style="padding-left:0"><li class="banner-funding"></li><li class="banner-research"></li><li class="banner-ppi"></li><li class="banner-partnerships"></li><li class="banner-industry"></li>-->
<!--                <li class="banner-faculty"></li><li class="banner-nihrarea"></li><li class="banner-about"></li><li class="banner-news"></li></ul>-->
<!--        </div>-->
        <div class="header-netscc">
            <div class="container">
                <p style="margin-top:18px; color:#fff;">Business Intelligence Portal</p>
            </div>
        </div>


        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-8" id="NKRD">
                <h3>NETSCC - Key Reports & Datasets</h3>
                <span><a src="http://srv00901/QvAJAXZfc/opendoc.htm?document=UserDocs%2FData%20Quality%20Dashboard.qvw&amp;host=Local">Data Quality Dashboard</a></span>
                <p>Lorem ipsum dolor sit amet.</p>
            </div>
            <div class="col-xs-6 col-md-4" id="NETSCCD">

            </div>
        </div>
        <div class="row">
            <div class="col-xs-6 col-md-4" id="External">" "</div>
            <div class="col-xs-6 col-md-4" id="NIHRD">" "</div>
            <div class="col-xs-6 col-md-4" id="Portfolio">" "</div>
        </div>
        <div class="row">
            <div class="col-xs-6" id="Help">" "</div>
            <div class="col-xs-6" id="Sharepoint">" "</div>
        </div>

        <footer class="netscc-footer">
            <div style="padding-top: 7px; padding-left: 8px;"><span id="year-copy"></span> &copy; <?php echo date("Y") ?> - Created by the <strong>NETSCC Information Systems Team</strong></div>
        </footer>
    </div>


    </body>
</html>
